### ISSUE TITLE
Supporting explicit Block RAM generation

### ISSUE THREAD

**Issue by iitaku** [PyHDI/veriloggen#22]
I'm requesting to make it possible to treat Block RAM explicitly in veriloggen. I want to create line-buffer which is composed of register and BRAM.

**Comment by shtaxxx** [comment]
veriloggen 1.7.0 supports two intermediate buffers (RingBuffer and Scracthpad) in Stream mode. RingBuffer is a BRAM-based extension for delayed values, such like var.prev(delay_size). Though the original prev() consumes Regs to store the delayed values, RingBuffer utilizes BRAM for longer delay intervals. Scratchpad is another extension that supports explicit addressing of read/write for delayed values. 
Please try it! Thanks for your comment.
